id: I64626222
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:12:49+00:00'
last_modified: '2022-06-16T04:49:08.854732+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6134
  title: འཛམ་གླིང་གནའ་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    BBC5:
      image_group_id: I1KG8441
      title: Volume 1 of 'dzam gling gna' rabs lo rgyus kyi gtam rgyud/
      total_pages: 432
      order: 1
      base_file: BBC5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
